@startuml

class Customer {
    name

    +add_rental()
    +statement()
    -total_charge()
    -total_frequent_renter_points()


}

class Rental {

    days_rented
    +charge()
    +frequent_renter_points()
    -eligible_for_bonus?()
}

class Movie {
    title
    price_code
    +charge()
}

Rental "1" *--> "1" Movie: movie
Customer "1" *--> "*" Rental: rentals [ ]

@enduml